### ISSUE TITLE
[DEV]  Requêter Wikidata selon la présence de P2040 ainsi que d'une chaîne de caractère incluse dans le label

### ISSUE THREAD

**Issue by thepriben** [okfnfr/CITES-biodiversity#12]
-

**Comment by itly314** [comment]
Salut @benprieur, voici une requête SPARQL qui devrait faire l'affaire. Fais-moi savoir si ça corréspond à ce que tu cherchais ou s'il faut la modifier.

```
# Requêter selon la présence d'une chaîne de caractères dans le *nom scientific*
# ainsi que la présence d'un ID CITES (P2040)
# Ex: trouver toutes les espèces dont le nom scientific contient la chaîne "panther"
#
SELECT ?idCITES ?item ?itemLabel ?nomScientific ?taxonRank 
WHERE {
  ?item wdt:P2040 ?idCITES .
  ?item wdt:P225 ?nomScientific . 
  ?item wdt:P105 ?taxonRank  # retourner le taxon rank

  FILTER(CONTAINS(LCASE(?nomScientific), "panther")) # critère de recherche: "panther" (en miniscule)
        
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }  # extraire les ?itemLabel en anglais
}
```
Pour exécuter, cliquer [ici](https://tinyurl.com/s7o5gw6)

**Comment by thepriben** [comment]
@itly314 merci :) La version actuelle de la requête est là https://github.com/benprieur/WildLife/blob/master/wikidata.py

Je la modifie ce soir avec ta proposition, histoire d'avoir une recherche soit sur le label (fr pour l'instant) soit sur le nom scientifique.

Merci encore.
