### ISSUE TITLE
[DEV] Afficher de manière intelligible les propriétés relatives à un résultat (taxonomie, espèce de rang supérieur etc.)

### ISSUE THREAD

**Issue by thepriben** [okfnfr/CITES-biodiversity#14]

**Comment by cecilaki** [comment]
Définir la notion d' "intelligible"

**Comment by thepriben** [comment]
En fait une partie des infos étaient sous forme Q123456 au lieu d'afficher sous-espèce. Il s'agissait de modifier la requête SPARQL en conséquence.
