### ISSUE TITLE
[DEV] animation d'attente de l'appel asynchrone

### ISSUE THREAD

**Issue by thepriben** [okfnfr/CITES-biodiversity#15]

**Comment by cecilaki** [comment]
Je ne suis pas sûre de bien comprendre cette tâche :) Quelle animation, où, et quel appel ?

**Comment by thepriben** [comment]
Mettre une petite animation qui tourne le temps que les données arrivent (vraiment utile tant qu'on va chercher les données à la volée sur Wikidata).
