### ISSUE TITLE
[DEV] Investiguer le pb de l'erreur 500 

### ISSUE THREAD

**Issue by cecilaki** [okfnfr/CITES-biodiversity#21]
* Scénario 
L'utilisateur réalise une recherche et la recherche aboutit sur une erreur 500

**Comment by thepriben** [comment]
La dernière version en ligne https://wildlifebpr.herokuapp.com/ doit consolider ce point. Normalement, plus de pbs http500 en vue. On réouvrira le ticket au besoin.
